---
name: ImagicalPlugInstaller
author: Ad5001
version: "1.0"
api: [1.14.0, 2.0.0]
main: Ad5001\ImagicalPlugInstaller\Main
commands: 
    installpl:
      description: "Install plugins from ImagicalMine"
      usage: "/installpl <plugins>"
      permission: ipi.install
permissions: 
    ipi.installpl:
     description: "Install plugins from ImagicalMine"
     default: op
...
